### NumPy offers much easier way to manipulate list/array elements
### You can save repeating the operation via a loop, i.e., single step is sufficient to operate on entire list

# Operations on NumPy arrays

### Multiply elements by 2

In [15]:
# Import the numpy package as np
import numpy as np

array1 = np.array([1,2,3,4])
array2 = 2*array1
array2

array([2, 4, 6, 8])

### Conditional processing on elements

In [16]:
# Find which elements are greater than or equal to 3
array1 = np.array([1,2,3,4])
array4 = (array1 >= 3)
array4

array([False, False,  True,  True])

### Adding/Subtracting/Multiplying two arrays (corresponding elements)

In [17]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

arraySum = array1 + array2
print ("arraySum: ", arraySum)



arraySum:  [11 22 33 44]


In [18]:
arrayDiff = array1 - array2
print ("arrayDiff: ", arrayDiff)

arrayDiff:  [ 9 18 27 36]


In [19]:
arrayProd = array1 * array2
print ("arrayProd: ", arrayProd)

arrayProd:  [ 10  40  90 160]


In [20]:
arrayDivide = array1 / array2
print ("arrayDivide: ", arrayDivide)

arrayDivide:  [10. 10. 10. 10.]


### Creating NumPy arrays from lists

In [21]:
# Create 2 new lists: height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

# Print the result
print(np_height)
print(np_weight)

[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]
