### Numpy performs advanced operations on List

In [2]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

# Print the result
print(np_height)
print(np_weight)

[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]


# Operations on Numpy array elements

### Multiply elements by 2

In [4]:
array1 = np.array([1,2,3,4])
array2 = 2*array1
array2

array([2, 4, 6, 8])

### Squaring the elements

In [5]:
array3 = array1**2
array3

array([ 1,  4,  9, 16], dtype=int32)

### Conditional processing on elements

In [6]:
array4 = (array1 >= 3)
array4

array([False, False,  True,  True])